# Generated by Django 6.0.5 on 2026-05-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='concert_posters/'),
        ),
    ]
